production.mode=false

spring.application.name=badasscouncil-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/badasscouncil
spring.datasource.username=badasscouncil
spring.datasource.password=Atari$Impact2024
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.messages.basename=messages,langs.messages

spring.servlet.multipart.max-file-size=2048MB
spring.servlet.multipart.max-request-size=2048MB

#spring.jpa.show-sql=true

logging.level.org.springframework=INFO

server.port=8443
server.ssl.enabled=true
server.ssl.key-store=classpath:springboot.p12
server.ssl.key-store-password=password
server.ssl.key-store-type=pkcs12
server.ssl.key-alias=springboot
server.ssl.key-password: password
server.servlet.context-path=/demovote-api/v1

cors.allow.origin=https://localhost:4200

#logging.file.name=logs/badasscouncil.log

#logging.logback.rollingpolicy.file-name-pattern=logs/%d{yyyy-MM, aux}/demovote.%d{yyyy-MM-dd}.%i.log
#logging.logback.rollingpolicy.max-file-size=2MB
#logging.logback.rollingpolicy.total-size-cap=10MB
#logging.logback.rollingpolicy.max-history=5

admin.email.address=xxx.xxx@free.fr

webcams.cache.domain=www.triplea.fr

jwttoken.secret=ba3616c8d3ae19f146477fcfa46716b6df6d16d90c4d68dc160599be56f462a82012acd18c0bd082b16234c55050902382f8995d883833fd192ea09e04b4b6a3
jwttoken.expiration=900000 
jwttoken.jwtRefreshExpirationMs= 86400000
#jwttoken.expiration=60000 
#jwttoken.jwtRefreshExpirationMs= 120000

